### ISSUE TITLE
 Bonus exercise in Deep Learning ?

### ISSUE THREAD

**Issue by callmesora** [miguelriemoliveira/savi_22-23#7]
Hello!

I was just looking around trying to get a refresher on Computer Vision and ended up learning a lot I didn't know about OpenCV, awesome resource! Thank you for making this freely available.

Would the professor like me to add a small folder with a extra optional classification project with CNN's? It works with photos you can take from your phone- I was doing exercises to test myself and ended up doing some nice Jupyter Notebooks that can be run on Colab that I don't mind sharing if there is interest by the students. (approx 1-2 h for a student to complete the notebook)-

Thanks again for this awesome repo :- ) , I will keep following this class on youtube as well

**Comment by miguelriemoliveira** [comment]
Hi @callmesora ,

thanks for the kind words. 
I have a small example prepared in classification, which is the fashion mnist tutorial from pytorch, which I will adapt to make it more pedagogical.

In any case, if you have some ideas and suggestions they are more than welcome.
If you want to send me something do it by email because I have a private repo where I prepare everything and only then move it to this public repo.

I am searching for ideas for the final assignment. It should be complex, since we have groups of 3/4 and its worth a lot of the final mark. The idea righ tnow is to use synfeal from @DanielCoelho112  to provide images, and ask the students to design, train and test a localization network.
